services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tickets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: tickets_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "True"
      OPENAI_API_KEY: "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"
    depends_on:
      - db
    command: >
      sh -c "
      until nc -z db 5432;
      do
        echo 'Waiting for database...';
        sleep 1;
      done;
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend